version: "3.4"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-data:/data/db

  backend:
    build: .
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://root:password@mongo:27017/chifoumi?authSource=admin
      - NODE_ENV=dev
      - SECRET_KEY=foo
    depends_on:
      - mongo
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "server.js"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]

volumes:
  db-data: {}